<<<<<<< HEAD
# Goal - I have to Lint, Build and Test my code in CI/CD pipeline
# Push the image to DockerHub

name: CI

on:
  push:
    branches: [feat/matrix-docker-build ]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps :
      - name: Checkout code
        uses: actions/checkout@v7
      - name: setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies (npm packages)
        run: npm install
        working-directory: frontend
      - name: Lint code
        run: npm run lint
        working-directory: frontend
      - name: run tests
        run: npm run test
        working-directory: frontend
      

  lint-backend:
    runs-on: ubuntu-latest
    steps :
      - name: Checkout code
        uses: actions/checkout@v7
      - name: setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
          go-version-file: backend/go.mod
          check-latest: false
          cache-dependency-path: backend/go.sum
      - name: Install Go formatter
        run: go fmt
        working-directory: backend
      - name: Run Go Vet
        run: go vet
        working-directory: backend
      - name: run tests
        run: go test  
        working-directory: backend
      
  build-and-push:
    needs: [lint-frontend, lint-backend]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [frontend, backend]
    steps :
      - name: Checkout code
        uses: actions/checkout@v7
      - name : Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.folder }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devboard_${{ matrix.folder }}_ci:latest
    
  deploy :
    needs: [lint-frontend, lint-backend, build-and-push]
    uses : ./.github/workflows/cd.yml
    secrets: inherit

=======
# Goal - I have to Lint, Build, Test the code for Frontend & Backend
# then Push the images to DockerHub 
name: CI

on: 
    push:
        # paths:
        #   - '**'
        #   - '!.github/workflows/**'
        branches: [feat/matrix-docker-build]

jobs:
    lint-frontend:
        # Github runner
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup NodeJs
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json
            
            - name: Install npm Packages
              run: npm install
              working-directory: frontend

            - name: Run Linter
              run: npm run lint
              working-directory: frontend

            - name: Run Tests
              run: npm run test 
              working-directory: frontend
            
                
    lint-backend:
        # Github runner
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                go-version: '1.23'
                go-version-file: 'go.mod'
                cache-dependency-path: go.sum
            
            - name: Run Go Formatter
              run: go fmt
              working-directory: backend

            - name: Run Go Vet
              run: go vet
              working-directory: backend
            
            - name: Run Tests
              run: go test 
              working-directory: backend
          

    build-and-push:
        needs: [lint-frontend,lint-backend] 
        runs-on: ubuntu-latest
        strategy:
          matrix:
            folder: ['frontend','backend']
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7

            - name: Docker Setup [Login]
              uses: docker/login-action@v4
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v7
              with:
                context: ./${{ matrix.folder}}
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folder}}:latest
          

    deploy:
        needs: [lint-frontend,lint-backend,build-and-push]
        uses: ./.github/workflows/cd.yml
        secrets: inherit
>>>>>>> 862958614f77cbd11f1cbdf9250d57a9a33e8735
