# Goal : Build the image for Devboard frontend & Push to Docker hub
name : CI
on: 
  push:
    branches : [master]
jobs:
  Build and Push :
    runs-on: ubuntu-latest
    steps :
      - name : Checkout code
        uses : actions/checkout@v7
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker setup [Login]
        uses: docker/login-action@v4
