# Goal - to ensure my running application is free from OWASP top 10 vulnerabilities and security misconfigurations.

name : OWSAP ZAP DAST Scan

on:
  workflow_call:

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Wait for the application to be up and running
        run: |
          timeout 60s sh -c 'until curl -s https://${{ secrets.EC2_HOST }}:8080; do sleep 5; done'
       
      - name: Run OWASP ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          secrets: ${{ secrets.GITHUB_TOKEN }}
          target: "https://${{ secrets.EC2_HOST }}:8080"
          fail_action: false
          allow_issue_writing: false
