# Goal - To run the DevSecOps pipeline to ensure the code is secure and free from vulnerabilities.

name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:
    code-quality: #Code Stage
        uses: ./.github/workflows/code-quality.yml

    secret-scan: #Secret Scan Stage
        uses: ./.github/workflows/secret-scanning.yml

    dependency-scan: #Dependency Scan Stage
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan: #Dockerfile Scan Stage
        uses: ./.github/workflows/docker-scans.yml
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}