# Goal - To run the DevSecOps pipeline to ensure the code is secure and free from vulnerabilities.

name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:
#    ------------------   CI    --------------------
    code-quality: #Code Stage
        uses: ./.github/workflows/code-quality.yml

    secret-scan: #Secret Scan Stage
        uses: ./.github/workflows/secret-scanning.yml

    dependency-scan: #Dependency Scan Stage
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan: #Dockerfile Scan Stage
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit

    sonarqube-scan: #SonarQube Scan Stage
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit
    
    code-test: #Code Test Stage
        uses: ./.github/workflows/code-test.yml

    docker-push: #Docker Push Stage
        needs: [code-quality,secret-scan,dependency-scan,docker-scan,sonarqube-scan,code-test]
        uses: ./.github/workflows/docker-push.yml
        secrets: inherit

#  -------------------   CD    --------------------
    deploy: #Deploy Stage
        needs: [docker-push]
        uses: ./.github/workflows/cd.yml
        secrets: inherit

    dast-scan: #DAST Scan Stage
        needs: [deploy]
        uses: ./.github/workflows/dast.yml
        secrets: inherit