# Goal - to check whether the code has no security vulnerabilities and code quality issues.

name : Sonar Qube scan

on:
  workflow_call:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
